---
services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: on-failure:5
    ports:
      - 1025:1025
    networks:
      - app
    depends_on:
      keycloak:
        condition: service_healthy
      keycloakdb:
        condition: service_healthy
      clickhouse:
        db: service_healthy

  keycloak:
    image: keycloak-app
    #command: ['start-dev']
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://keycloakdb/keycloak

      KC_DB_USERNAME: keycloak # Make sure it matches the POSTGRES_USER below
      KC_DB_PASSWORD: password # Make sure it matches the POSTGRES_PASSWORD below

      KEYCLOAK_ADMIN: admin # Change this to a different username
      KEYCLOAK_ADMIN_PASSWORD: password # Change this to a better password

      KC_HEALTH_ENABLED: true
      KC_HTTP_RELATIVE_PATH: /auth
    ports:
      - "8089:8080"
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
      interval: 30s
      timeout: 10s
      retries: 3

  keycloakdb:
    image: postgres
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak # Change this to a different username
      POSTGRES_PASSWORD: password # Change this to a better password
    ports:
      - "8888:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  db:
    image: postgres
    container_name: backend-postgres
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: backend # Change this to a different username
      POSTGRES_PASSWORD: password # Change this to a better password
    ports:
      - "1330:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
