services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:3001
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - ASPNETCORE_URLS=http://+:3001
      - ASPNETCORE_ENVIRONMENT=Production
      # Cache & Database
      - NXTDatabase:Password=gAUzlli22pWMwel5wfqGrafusT4kJl0nPzz6acgsE3aRMDWUJHaQzCbgMZJzXEl0
      - NXTCache:Password=rn61FchILYS13tMe3mBVKL6sLKjtHx0PH9AvPeVuaNLqW2L97cv6ZUwPAuxwQB9B
      # Keycloak Authentication
      - Keycloak:realm=student
      - Keycloak:auth-server-url=https://auth.hamette.net
      - Keycloak:resource=intra
      - Keycloak:credentials:secret=8EliRmg5oMiq3UUAgFzPV00rY77fDxAo
      # Connection Strings
      - ConnectionStrings:Cache=31.187.76.65:1338,ssl=False,abortConnect=False
      - ConnectionStrings:DefaultConnection=Host=31.187.76.65; Port=1337; Database=postgres; Username=postgres;
    restart: unless-stopped
