// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NXTBackend.API.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NXTBackend.API.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250522153927_RemoveNotificationFields")]
    partial class RemoveNotificationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CollaboratorsOnCursi", b =>
                {
                    b.Property<Guid>("CollaboratedCursiId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollaboratorsId")
                        .HasColumnType("uuid");

                    b.HasKey("CollaboratedCursiId", "CollaboratorsId");

                    b.HasIndex("CollaboratorsId");

                    b.ToTable("CollaboratorsOnCursi");
                });

            modelBuilder.Entity("CollaboratorsOnGoals", b =>
                {
                    b.Property<Guid>("CollaboratedGoalsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollaboratorsId")
                        .HasColumnType("uuid");

                    b.HasKey("CollaboratedGoalsId", "CollaboratorsId");

                    b.HasIndex("CollaboratorsId");

                    b.ToTable("CollaboratorsOnGoals");
                });

            modelBuilder.Entity("LearningGoalProject", b =>
                {
                    b.Property<Guid>("GoalsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectsId")
                        .HasColumnType("uuid");

                    b.HasKey("GoalsId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("LearningGoalProject");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Cursus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("Deprecated")
                        .HasColumnType("boolean")
                        .HasColumnName("deprecated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markdown");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean")
                        .HasColumnName("public");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Track")
                        .HasColumnType("jsonb")
                        .HasColumnName("track");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Name");

                    b.HasIndex("Slug");

                    b.ToTable("tbl_cursus");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Evaluation.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markdown");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_comment");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Evaluation.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("tbl_feedback");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Evaluation.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<bool>("Anonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("anonymous");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FeedbackId")
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<Guid?>("RubricId")
                        .HasColumnType("uuid")
                        .HasColumnName("rubric_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_project_id");

                    b.Property<bool>("Validated")
                        .HasColumnType("boolean")
                        .HasColumnName("validated");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("RubricId");

                    b.HasIndex("UserProjectId");

                    b.ToTable("tbl_review");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Evaluation.Rubric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("GitInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("git_info_id");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markdown");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean")
                        .HasColumnName("public");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GitInfoId");

                    b.HasIndex("Name");

                    b.HasIndex("ProjectId");

                    b.ToTable("tbl_rubric");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markdown");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tbl_feature");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("tbl_feed");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Git", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("git_branch");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("git_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("git_name");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("git_namespace");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer")
                        .HasColumnName("git_owner");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer")
                        .HasColumnName("git_provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("git_url");

                    b.HasKey("Id");

                    b.ToTable("tbl_git");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.LearningGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("Deprecated")
                        .HasColumnType("boolean")
                        .HasColumnName("deprecated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Markdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("markdown");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean")
                        .HasColumnName("public");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Name");

                    b.HasIndex("Slug");

                    b.ToTable("tbl_learning_goal");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("tbl_notifications");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("Deprecated")
                        .HasColumnType("boolean")
                        .HasColumnName("deprecated");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("GitInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("git_info_id");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer")
                        .HasColumnName("max_members");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean")
                        .HasColumnName("public");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GitInfoId");

                    b.HasIndex("Name");

                    b.HasIndex("Slug");

                    b.ToTable("tbl_project");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Spotlight.SpotlightEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("ActionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_text");

                    b.Property<string>("BackgroundUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("background_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("href");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tbl_spotlight_event");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Spotlight.SpotlightEventAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dismissed");

                    b.Property<Guid>("SpotlightId")
                        .HasColumnType("uuid")
                        .HasColumnName("spotlight_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("tbl_spotlight_event_action");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.UserFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("VisibleFeeds")
                        .HasColumnType("integer")
                        .HasColumnName("visible_feed");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tbl_user_feed");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.Details", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("text")
                        .HasColumnName("github_url");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("LinkedinUrl")
                        .HasColumnType("text")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("Markdown")
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("bio");

                    b.Property<int>("NotificationPreference")
                        .HasColumnType("integer")
                        .HasColumnName("notification_preference");

                    b.Property<string>("RedditUrl")
                        .HasColumnType("text")
                        .HasColumnName("reddit_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_user_details");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("invite_state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("UserProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_project_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserProjectId");

                    b.ToTable("tbl_user_project_member");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DetailsId")
                        .HasColumnType("uuid")
                        .HasColumnName("details_id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserFeedId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_feed_id");

                    b.HasKey("Id");

                    b.HasIndex("DetailsId");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Login");

                    b.ToTable("tbl_user");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.UserCursus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CursusId")
                        .HasColumnType("uuid")
                        .HasColumnName("cursus_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CursusId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_user_cursus");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.UserGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserCursusId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_cursus_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.HasIndex("UserCursusId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_user_goal");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.UserProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("GitInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("git_info_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("RubricId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GitInfoId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RubricId");

                    b.ToTable("tbl_user_project");
                });

            modelBuilder.Entity("CollaboratorsOnCursi", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Cursus", null)
                        .WithMany()
                        .HasForeignKey("CollaboratedCursiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CollaboratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollaboratorsOnGoals", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.LearningGoal", null)
                        .WithMany()
                        .HasForeignKey("CollaboratedGoalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CollaboratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearningGoalProject", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.LearningGoal", null)
                        .WithMany()
                        .HasForeignKey("GoalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXTBackend.API.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Cursus", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "Creator")
                        .WithMany("CreatedCursus")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Evaluation.Comment", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Evaluation.Feedback", "Feedback")
                        .WithMany("Comments")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Evaluation.Feedback", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Evaluation.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Evaluation.Review", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Evaluation.Feedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FeedbackId");

                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "Reviewer")
                        .WithMany("Rubricer")
                        .HasForeignKey("ReviewerId");

                    b.HasOne("NXTBackend.API.Domain.Entities.Evaluation.Rubric", "Rubric")
                        .WithMany("Reviews")
                        .HasForeignKey("RubricId");

                    b.HasOne("NXTBackend.API.Domain.Entities.Users.UserProject", "UserProject")
                        .WithMany()
                        .HasForeignKey("UserProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feedback");

                    b.Navigation("Reviewer");

                    b.Navigation("Rubric");

                    b.Navigation("UserProject");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Evaluation.Rubric", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "Creator")
                        .WithMany("CreatedRubrics")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NXTBackend.API.Domain.Entities.Git", "GitInfo")
                        .WithMany("Rubrics")
                        .HasForeignKey("GitInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXTBackend.API.Domain.Entities.Project", "Project")
                        .WithMany("Rubrics")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("GitInfo");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Feed", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "Actor")
                        .WithMany("CreatedFeeds")
                        .HasForeignKey("ActorId");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.LearningGoal", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "Creator")
                        .WithMany("CreatedGoals")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Project", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "Creator")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NXTBackend.API.Domain.Entities.Git", "GitInfo")
                        .WithMany("Projects")
                        .HasForeignKey("GitInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("GitInfo");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.UserFeed", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "User")
                        .WithOne("UserFeed")
                        .HasForeignKey("NXTBackend.API.Domain.Entities.UserFeed", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.Details", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.Member", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "User")
                        .WithMany("ProjectMember")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NXTBackend.API.Domain.Entities.Users.UserProject", "UserProject")
                        .WithMany("Members")
                        .HasForeignKey("UserProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserProject");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Users.Details", "Details")
                        .WithMany()
                        .HasForeignKey("DetailsId");

                    b.Navigation("Details");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.UserCursus", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Cursus", "Cursus")
                        .WithMany("UserCursi")
                        .HasForeignKey("CursusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "User")
                        .WithMany("UserCursi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cursus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.UserGoal", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.LearningGoal", "Goal")
                        .WithMany("UserGoals")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NXTBackend.API.Domain.Entities.Users.UserCursus", "UserCursus")
                        .WithMany("UserGoals")
                        .HasForeignKey("UserCursusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NXTBackend.API.Domain.Entities.Users.User", "User")
                        .WithMany("UserGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("User");

                    b.Navigation("UserCursus");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.UserProject", b =>
                {
                    b.HasOne("NXTBackend.API.Domain.Entities.Git", "GitInfo")
                        .WithMany("UserProjects")
                        .HasForeignKey("GitInfoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NXTBackend.API.Domain.Entities.Project", "Project")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NXTBackend.API.Domain.Entities.Evaluation.Rubric", null)
                        .WithMany("UserProjects")
                        .HasForeignKey("RubricId");

                    b.Navigation("GitInfo");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Cursus", b =>
                {
                    b.Navigation("UserCursi");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Evaluation.Feedback", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Evaluation.Rubric", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Git", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Rubrics");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.LearningGoal", b =>
                {
                    b.Navigation("UserGoals");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Project", b =>
                {
                    b.Navigation("Rubrics");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CreatedCursus");

                    b.Navigation("CreatedFeeds");

                    b.Navigation("CreatedGoals");

                    b.Navigation("CreatedProjects");

                    b.Navigation("CreatedRubrics");

                    b.Navigation("ProjectMember");

                    b.Navigation("Rubricer");

                    b.Navigation("UserCursi");

                    b.Navigation("UserFeed");

                    b.Navigation("UserGoals");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.UserCursus", b =>
                {
                    b.Navigation("UserGoals");
                });

            modelBuilder.Entity("NXTBackend.API.Domain.Entities.Users.UserProject", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
