name: Svelte

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        working-directory: frontend
        run: bun --bun install
      - name: Build
        working-directory: frontend
        run: bun --bun run build
